### PR TITLE
Simplify software tests

### PR DESCRIPTION
**Pull request by atd-schubert**
This is a @marcjansen flavored PR. Thanks for your help in Essen again! leaflet-ng2 is loosing weight ;)

Maybe @marcjansen want to make a review, too.

### CODE REVIEW

**Comment by atd-schubert** [comment]
I don't have any problems on my local computer. I don't know why Travis has errors there!

**Comment by atd-schubert** [comment]
Now it works and can be merged! @OpenSteveMap

**Comment by marcjansen** [comment]
A net minus of over 6000 lines!?! Absolutely great.

I just scanned the diff, but this looks very good to me. I am plus one on merging.

This massive effort is much appreciated.

**Review by OpenSteveMap — APPROVED** [review]
great

**Pull request merged**
